// <auto-generated />
namespace EduMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createControlCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createControlCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201910070155553_createControlCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
